/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatioRouteImport } from './routes/ratio'
import { Route as IndexRouteImport } from './routes/index'

const RatioRoute = RatioRouteImport.update({
  id: '/ratio',
  path: '/ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ratio': typeof RatioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ratio': typeof RatioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ratio': typeof RatioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ratio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ratio'
  id: '__root__' | '/' | '/ratio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RatioRoute: typeof RatioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ratio': {
      id: '/ratio'
      path: '/ratio'
      fullPath: '/ratio'
      preLoaderRoute: typeof RatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RatioRoute: RatioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
